parameters:
- name: environment
  displayName: Environment
  type: string
  default: dev
  values:
  - dev
  - uat
  - prod

trigger:
- main

variables:
- name: appName
  value: enterprise-devops-lab

- name: buildConfiguration
  value: Release
  
pool:
  vmImage: ubuntu-latest

steps:

- script: |
    echo "===== Build Information ====="
    echo "Repository: $(Build.Repository.Name)"
    echo "Branch: $(Build.SourceBranch)"
    echo "Commit: $(Build.SourceVersion)"
    echo "Agent Name: $(Agent.Name)"
    echo "Agent OS: $(Agent.OS)"
    echo "Build Number: $(Build.BuildNumber)"
    echo "Application: $(appName)"
    echo "Configuration: $(buildConfiguration)"
    echo "Environment: ${{ parameters.environment }}"
  displayName: "Display Pipeline Information"
