apiVersion: v1
kind: Service

metadata:
  name: enterprise-devops-lab
  namespace: petclinic

spec:
  selector:
    app: enterprise-devops-lab

  ports:
  - port: 80
    targetPort: 8080

  type: ClusterIP
